CREATE DATABASE KASZNAR_DB;
USE KASZNAR_DB

IF OBJECT_ID('Usuario') IS NULL
BEGIN
	CREATE TABLE USUARIO(
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	LOGINUSER VARCHAR(10) NOT NULL,
	SENHA VARCHAR(15) NOT NULL,
	ATIVO BIT NOT NULL)

	ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID);
	ALTER TABLE USUARIO ADD CONSTRAINT UQ_USUARIO UNIQUE (ID);
END
GO

INSERT INTO USUARIO VALUES('Administrador', 'Admin', 'Admin', 'true')

IF OBJECT_ID('SETOR') IS NULL
BEGIN
	CREATE TABLE SETOR(
	ID INT NOT NULL IDENTITY(1,1),
	DESCRICAO VARCHAR(100) NOT NULL,
	ATIVIDADE VARCHAR(1000) NOT NULL,
	ATIVO BIT NOT NULL)

	ALTER TABLE SETOR ADD CONSTRAINT PK_SETOR PRIMARY KEY (ID);
	ALTER TABLE SETOR ADD CONSTRAINT UQ_SETOR UNIQUE (ID);
END
GO
	
IF OBJECT_ID('CARGO') IS NULL
BEGIN
	CREATE TABLE CARGO(
	ID INT NOT NULL IDENTITY(1,1),
	DESCRICAO VARCHAR(100) NOT NULL,
	ATIVIDADE VARCHAR(1000) NOT NULL,
	ATIVO BIT NOT NULL)

	ALTER TABLE CARGO ADD CONSTRAINT PK_CARGO PRIMARY KEY (ID);
	ALTER TABLE CARGO ADD CONSTRAINT UQ_CARGO UNIQUE (ID);
END
GO


IF OBJECT_ID('COLABORADOR') IS NULL
BEGIN
	CREATE TABLE COLABORADOR(
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(200) NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	IDSETOR INT NOT NULL,
	IDCARGO INT NOT NULL,
	ATIVO BIT NOT NULL,
	IDSUPERIORIMEDIATO INT NULL)

	ALTER TABLE COLABORADOR ADD CONSTRAINT PK_COLABORADOR PRIMARY KEY (ID);
	ALTER TABLE COLABORADOR ADD CONSTRAINT UQ_COLABORADOR UNIQUE (ID);
	ALTER TABLE COLABORADOR ADD CONSTRAINT FK_COLABORADOR_SETOR FOREIGN KEY (IDSETOR) REFERENCES SETOR(ID);
	ALTER TABLE COLABORADOR ADD CONSTRAINT FK_COLABORADOR_CARGO FOREIGN KEY (IDCARGO) REFERENCES CARGO(ID);
	ALTER TABLE COLABORADOR ADD CONSTRAINT FK_COLABORADOR_SUPERIOR FOREIGN KEY (IDSUPERIORIMEDIATO) REFERENCES COLABORADOR(ID);
END
GO

--ALTER TABLE TB_SETOR ADD ID_USUARIO_CADASTRO INT NOT NULL;
--ALTER TABLE TB_SETOR ADD DT_CADASTRO DATETIME NOT NULL;
--ALTER TABLE TB_SETOR ADD ID_USUARIO_ALTERACAO INT NULL;
--ALTER TABLE TB_SETOR ADD DT_ALTERACAO DATETIME NULL;
--GO

--ALTER TABLE TB_CARGO ADD ID_USUARIO_CADASTRO INT NOT NULL;
--ALTER TABLE TB_CARGO ADD DT_CADASTRO DATETIME NOT NULL;
--ALTER TABLE TB_CARGO ADD ID_USUARIO_ALTERACAO INT NULL;
--ALTER TABLE TB_CARGO ADD DT_ALTERACAO DATETIME NULL;
--GO

--ALTER TABLE TB_COLABORADOR ADD ID_USUARIO_CADASTRO INT NOT NULL;
--ALTER TABLE TB_COLABORADOR ADD DT_CADASTRO DATETIME NOT NULL;
--ALTER TABLE TB_COLABORADOR ADD ID_USUARIO_ALTERACAO INT NULL;
--ALTER TABLE TB_COLABORADOR ADD DT_ALTERACAO DATETIME NULL;
--GO

